name: CI Pipeline
on:
  push:
    branches: [ main ]
jobs:
  checkout_and_compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run the Maven compile phase
        run:  mvn compile
      - name: Run the Maven package phase
        run:  mvn package
      - name: Upload Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: gas.jar
          path: target/*.jar
      
